version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ${container_name}
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${database_name}
      MYSQL_ROOT_PASSWORD: ${database_password}
    volumes:
      - mysql_cars:/var/lib/mysql

volumes:
  ${volume_name}: