version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_crudSonar
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crudSonar
      MYSQL_ROOT_PASSWORD: hgrDWRdzNh4LbWd61XvZJ86PcEt9mJ3jHNsmqW8LkHA=
    volumes:
      - mysql_crudSonar:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migrate
    command: -url=jdbc:mysql://mysql:3306/crudSonar?allowPublicKeyRetrieval=true -user=root -password=hgrDWRdzNh4LbWd61XvZJ86PcEt9mJ3jHNsmqW8LkHA= -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  mysql_crudSonar: